version: 2
updates:
  # Enable version updates for Swift Package Manager
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
