name: Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build -v
